apiVersion: v1
kind: ConfigMap
metadata:
  name: data-hunt-backup-config
  namespace: data-hunt
  labels:
    app.kubernetes.io/name: data-hunt-postgres-backup
    app.kubernetes.io/part-of: data-hunt
data:
  S3_ENDPOINT: https://sg-sin-1.linodeobjects.com
  S3_BUCKET: data-hunt-backups
  S3_PREFIX: data-hunt-postgres/daily
  AWS_DEFAULT_REGION: us-east-1
