apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-hunt
  namespace: agents
  labels:
    app: data-hunt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-hunt
  template:
    metadata:
      labels:
        app: data-hunt
    spec:
      containers:
      - name: data-hunt
        image: dushes/data-hunt
        ports:
        - containerPort: 8111
          name: http
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8111
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8111
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        env:
          - name: PORT
            value: "8111"
          - name: DEBANK_ACCESS_KEY
            value: adad733347b6c241560b5c5bd1b7c9d51bd5599a
          - name: UPDATE_INTERVAL
            value: 12h
          - name: RUN_ON_STARTUP
            value: "false"
          - name: ACCESS_TOKEN_EXPIRE_MINUTES
            value: "525600"
          - name: SECRET_KEY
            value: 09d27e094faa6cb2556c818136b7a9563b03f7099f6f0a4caa6df63b81e8d3e7
          - name: COINMARKETCAP_API_KEY
            value: "d76e9cadd2104c0b99891480c5184f9c"
          - name: COINMARKETCAP_CACHE_TTL_SECONDS
            value: "3600"
          - name: DATABASE_URL
            value: postgresql://data-hunt:lsdahfl34w978efysdlifh4378wei@postgres-service.postgres.svc.cluster.local/data-hunt