"""Add ProjectDict model

Revision ID: 08d100e525a4
Revises: 63ad7bf5477d
Create Date: 2026-01-05 11:27:42.450669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d100e525a4'
down_revision: Union[str, None] = '63ad7bf5477d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_dict',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chain', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('site_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_dict')
    # ### end Alembic commands ###
