"""add is_scam to address_history

Revision ID: 0aa3e6ff904e
Revises: 89d2f4d7273f
Create Date: 2026-01-05 22:20:43.984106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa3e6ff904e'
down_revision: Union[str, None] = '89d2f4d7273f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_history', sa.Column('is_scam', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address_history', 'is_scam')
    # ### end Alembic commands ###
