"""add_balance_to_account

Revision ID: 63ad7bf5477d
Revises: cda4d87b498b
Create Date: 2025-12-17 15:49:17.568993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ad7bf5477d'
down_revision: Union[str, None] = 'cda4d87b498b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'balance')
    # ### end Alembic commands ###
