"""add_address_to_address_history_pk

Revision ID: 75503c3455a8
Revises: 0aa3e6ff904e
Create Date: 2026-01-06 14:59:19.719653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75503c3455a8'
down_revision: Union[str, None] = '0aa3e6ff904e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM address_history")
    op.add_column('address_history', sa.Column('address', sa.String(), nullable=False))
    op.drop_constraint('address_history_pkey', 'address_history', type_='primary')
    op.create_primary_key('address_history_pkey', 'address_history', ['id', 'chain', 'address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address_history', 'address')
    # ### end Alembic commands ###
