"""Add AddressHistory model

Revision ID: 89d2f4d7273f
Revises: a33f38303a6d
Create Date: 2026-01-05 12:29:10.517799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89d2f4d7273f'
down_revision: Union[str, None] = 'a33f38303a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('cate_id', sa.String(), nullable=True),
    sa.Column('time_at', sa.Integer(), nullable=True),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', 'chain')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address_history')
    # ### end Alembic commands ###
