"""Add network to account_address

Revision ID: 8cefafaad1c0
Revises: a8b4138aa30d
Create Date: 2025-12-15 12:22:42.313014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cefafaad1c0'
down_revision: Union[str, None] = 'a8b4138aa30d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_address', sa.Column('network', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_address', 'network')
    # ### end Alembic commands ###
