"""Add CEXDict model

Revision ID: a33f38303a6d
Revises: f68fa403085f
Create Date: 2026-01-05 12:04:41.048456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33f38303a6d'
down_revision: Union[str, None] = 'f68fa403085f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cex_dict',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cex_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('is_deposit', sa.Boolean(), nullable=True),
    sa.Column('is_collect', sa.Boolean(), nullable=True),
    sa.Column('is_gastopup', sa.Boolean(), nullable=True),
    sa.Column('is_vault', sa.Boolean(), nullable=True),
    sa.Column('is_withdraw', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cex_dict')
    # ### end Alembic commands ###
