"""add_debank_request_table

Revision ID: cda4d87b498b
Revises: 0c7577e990f6
Create Date: 2025-12-17 15:09:03.060787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cda4d87b498b'
down_revision: Union[str, None] = '0c7577e990f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debank_request',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('params', sa.String(), nullable=True),
    sa.Column('response_json', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debank_request_account_id'), 'debank_request', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_debank_request_account_id'), table_name='debank_request')
    op.drop_table('debank_request')
    # ### end Alembic commands ###
