"""Add TokenDict model

Revision ID: f68fa403085f
Revises: 08d100e525a4
Create Date: 2026-01-05 11:34:23.507518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f68fa403085f'
down_revision: Union[str, None] = '08d100e525a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_dict',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('display_symbol', sa.String(), nullable=True),
    sa.Column('optimized_symbol', sa.String(), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('protocol_id', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_24h_change', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_core', sa.Boolean(), nullable=True),
    sa.Column('is_wallet', sa.Boolean(), nullable=True),
    sa.Column('is_scam', sa.Boolean(), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=True),
    sa.Column('credit_score', sa.Float(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('time_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'project_dict', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_dict', type_='unique')
    op.drop_table('token_dict')
    # ### end Alembic commands ###
